### ISSUE TITLE
Unity v0.1.2 IOS Build getting pink material on model [BUG]

### ISSUE THREAD

**Issue by Jordan-s11** [Volograms/volograms_unity_plugin#21] opened 2022-05-20 02:22 UTC
**Describe the bug**
Building on IPhone 13 max the mp4 texture never shows just the model animating with a pink material.

**To Reproduce**
1. Using Unity version 2021.1.24 with URP version 11 and AR Foundation
2. Add Volplayer component to a gameobject and reference assets from streaming assets folder.
3. Build onto device (Iphone 13 pro max)
4. See that app either crashes or periodically drops frames almost to a halt and the volu model plays animation with pink material.

**Expected behavior**
For smooth playback of mp4 texture

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Monterey 21.0.1

**Smartphone (please complete the following information):**
 - Device: Iphone 13 pro max
 

**Additional context**
Add any other context about the problem here. Some suggestions
- v0.1.2
- default volu in the package

**Comment by capnramses** [comment] 2022-05-23 09:41
Hi @Jordan-s11 

I asked the team, who were not able to reproduce the problem on an iOS export today.

However, there may be several issues at play:

RE: missing texture:

* The material that comes with the plugin is not compatible with URP.
* Could you try a non-URP build first to see if it gets past the pink (missing) material issue?
* If that works and you need URP you'll need to make a new material that's URP-compatible.

RE: performance

* I suspect this might be log spam on errors with materials or textures.
* Please enable the logging option in the Volograms game object component, and have the phone plugged into xcode when running - this should show you any logs being spat out.
* Please capture those and attach to this ticket.

RE: crashes

* We're not sure why this is happening yet but it's possibly an unrelated issue to address separately. I'd fix the material first. Hopefully the logs shed some insight there, but it's likely to be another bug.

**Comment by Jordan-s11** [comment] 2022-05-23 17:58
Interesting, Ok I will give those a shot and see what happens.

**Comment by Jordan-s11** [comment] 2022-05-24 01:00
@capnramses Got it working thanks! Looks like the default instantiated texture was not compatible with URP.

**Comment by Jordan-s11** [comment] 2022-05-24 02:17
@capnramses Are you guys seeing any frame drops? I have got the textures to work but am still experiencing the frame drops. I have added the logs (error only and nothing comes up that I can see, will try all logs next)

**Comment by Jordan-s11** [comment] 2022-05-24 02:30
It seems that even with the texture working the frame drop is still caused by the VolPlayer.Update() function

**Comment by capnramses** [comment] 2022-05-25 12:28
That's great news @Jordan-s11 !

On iOS the framerate should be okay on most devices - check the resolution of the video texture.
Using a Volu capture with 1024x1024 should be okay on most devices.
Some of the studio captures have 2048x2048 which may be a bit slower to update.
If you've captured a vologram in Volu you can compare that between Volu and your app - it should possible to get about the same performance since the same update code is running in both.
We have a few issues tagged to improve the performance further - right now the main bottleneck is the video decoding time.

**Comment by capnramses** [comment] 2022-05-25 12:30
Did the crashes stop when the material was changed?
If you're satisfied we can close out this ticket.

**Comment by Jordan-s11** [comment] 2022-05-27 01:57
@capnramses Yes it seems to no longer crash. Ok I am currently trying above to see if there are major frame changes. Thanks

**Comment by capnramses** [comment] 2022-05-30 10:05
Okay, I'm going to close this as a crash bug and we can track any performance issues separately.

**Closed by capnramses** 2022-05-30 10:05 UTC
Labels: bug, performance
